version: '3.8'

# DevAssist Pro Production Configuration
# Ubuntu 22.04 Server: 46.149.71.162
# One-command deployment setup

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: devassist_postgres_prod
    environment:
      POSTGRES_DB: devassist_pro
      POSTGRES_USER: devassist_user
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-devassist_secure_password_2024}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U devassist_user -d devassist_pro"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - devassist_network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: devassist_redis_prod
    command: redis-server --requirepass ${REDIS_PASSWORD:-redis_secure_password_2024}
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "--no-auth-warning", "-a", "${REDIS_PASSWORD:-redis_secure_password_2024}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    restart: unless-stopped
    networks:
      - devassist_network

  # Backend Application (FastAPI)
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile.monolith
      args:
        - ENVIRONMENT=production
    container_name: devassist_app_prod
    environment:
      # Database Configuration
      POSTGRES_URL: postgresql://devassist_user:${POSTGRES_PASSWORD:-devassist_secure_password_2024}@postgres:5432/devassist_pro
      DATABASE_URL: postgresql://devassist_user:${POSTGRES_PASSWORD:-devassist_secure_password_2024}@postgres:5432/devassist_pro
      
      # Redis Configuration
      REDIS_URL: redis://:${REDIS_PASSWORD:-redis_secure_password_2024}@redis:6379/0
      
      # Application Configuration
      ENVIRONMENT: production
      DEBUG: false
      LOG_LEVEL: INFO
      HOST: 0.0.0.0
      PORT: 8000
      
      # Security
      JWT_SECRET: ${JWT_SECRET:-your_jwt_secret_key_minimum_32_characters_long}
      SECRET_KEY: ${JWT_SECRET:-your_jwt_secret_key_minimum_32_characters_long}
      
      # CORS Configuration
      ALLOWED_ORIGINS: http://46.149.71.162,http://localhost,https://46.149.71.162
      CORS_ORIGINS: http://46.149.71.162,http://localhost,https://46.149.71.162
      
      # File Upload Configuration
      MAX_FILE_SIZE: 50MB
      SUPPORTED_FORMATS: pdf,docx,doc,txt,xlsx
      UPLOAD_DIR: /app/data/uploads
      
      # AI Provider Configuration
      ANTHROPIC_API_KEY: ${ANTHROPIC_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GOOGLE_API_KEY: ${GOOGLE_API_KEY}
      USE_REAL_API: true
      
      # Performance Configuration
      WORKERS: 4
      MAX_REQUESTS: 1000
      MAX_REQUESTS_JITTER: 100
      TIMEOUT: 120
      
    volumes:
      - app_data:/app/data
      - app_logs:/app/logs
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    restart: unless-stopped
    networks:
      - devassist_network

  # Frontend Application (React SPA)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.prod
      args:
        - REACT_APP_API_URL=http://46.149.71.162/api
        - REACT_APP_WS_URL=ws://46.149.71.162/ws
        - REACT_APP_USE_REAL_API=true
        - NODE_ENV=production
    container_name: devassist_frontend_prod
    environment:
      - NODE_ENV=production
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/frontend-health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - devassist_network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: devassist_nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - nginx_logs:/var/log/nginx
    depends_on:
      app:
        condition: service_healthy
      frontend:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    restart: unless-stopped
    networks:
      - devassist_network

# Named Volumes для persistent storage
volumes:
  postgres_data:
    driver: local
    name: devassist_postgres_data
  redis_data:
    driver: local
    name: devassist_redis_data
  app_data:
    driver: local
    name: devassist_app_data
  app_logs:
    driver: local
    name: devassist_app_logs
  nginx_logs:
    driver: local
    name: devassist_nginx_logs

# Networks
networks:
  devassist_network:
    driver: bridge
    name: devassist_prod_network
    ipam:
      config:
        - subnet: 172.20.0.0/16