"""Add V3 Analysis models for 10-criteria system

Revision ID: 0003_v3_analysis_models
Revises: 0002_dashboard_models
Create Date: 2025-01-11 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0003_v3_analysis_models'
down_revision = '0002_dashboard_models'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Create V3 Analysis table
    op.create_table('v3_analyses',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('analysis_type', sa.String(length=50), nullable=False),
        sa.Column('status', sa.String(length=50), nullable=False),
        sa.Column('overall_score', sa.Integer(), nullable=True),
        sa.Column('weighted_score', sa.Float(), nullable=True),
        sa.Column('company_name', sa.String(length=255), nullable=True),
        sa.Column('executive_summary', sa.Text(), nullable=True),
        sa.Column('criteria_results', sa.JSON(), nullable=True),
        sa.Column('criteria_weights', sa.JSON(), nullable=True),
        sa.Column('currency_data', sa.JSON(), nullable=True),
        sa.Column('extracted_tables', sa.JSON(), nullable=True),
        sa.Column('charts_data', sa.JSON(), nullable=True),
        sa.Column('processing_time', sa.Float(), nullable=True),
        sa.Column('risk_level', sa.String(length=50), nullable=True),
        sa.Column('recommendations', sa.JSON(), nullable=True),
        sa.Column('project_id', sa.Integer(), nullable=False),
        sa.Column('tz_document_id', sa.Integer(), nullable=True),
        sa.Column('created_by_id', sa.Integer(), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
        sa.ForeignKeyConstraint(['tz_document_id'], ['documents.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v3_analyses_id'), 'v3_analyses', ['id'], unique=False)
    
    # Create V3 Analysis Documents junction table
    op.create_table('v3_analysis_documents',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('v3_analysis_id', sa.Integer(), nullable=False),
        sa.Column('document_id', sa.Integer(), nullable=False),
        sa.Column('extraction_data', sa.JSON(), nullable=True),
        sa.Column('document_score', sa.Float(), nullable=True),
        sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ),
        sa.ForeignKeyConstraint(['v3_analysis_id'], ['v3_analyses.id'], ),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_v3_analysis_documents_id'), 'v3_analysis_documents', ['id'], unique=False)
    
    # Create Criteria Weights Presets table
    op.create_table('criteria_weights_presets',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(length=100), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('is_system', sa.Boolean(), nullable=False),
        sa.Column('budget_compliance', sa.Float(), nullable=False),
        sa.Column('timeline_compliance', sa.Float(), nullable=False),
        sa.Column('technical_compliance', sa.Float(), nullable=False),
        sa.Column('team_expertise', sa.Float(), nullable=False),
        sa.Column('functional_coverage', sa.Float(), nullable=False),
        sa.Column('quality_assurance', sa.Float(), nullable=False),
        sa.Column('development_methodology', sa.Float(), nullable=False),
        sa.Column('scalability', sa.Float(), nullable=False),
        sa.Column('communication', sa.Float(), nullable=False),
        sa.Column('added_value', sa.Float(), nullable=False),
        sa.Column('created_by_id', sa.Integer(), nullable=True),
        sa.Column('organization_id', sa.Integer(), nullable=True),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ),
        sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
        sa.PrimaryKeyConstraint('id'),
        sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_criteria_weights_presets_id'), 'criteria_weights_presets', ['id'], unique=False)
    
    # Set default values for existing columns
    op.execute("UPDATE v3_analyses SET analysis_type = 'v3_expert' WHERE analysis_type IS NULL")
    op.execute("UPDATE v3_analyses SET status = 'pending' WHERE status IS NULL")
    op.execute("UPDATE criteria_weights_presets SET is_system = false WHERE is_system IS NULL")
    op.execute("UPDATE criteria_weights_presets SET budget_compliance = 0.15 WHERE budget_compliance IS NULL")
    op.execute("UPDATE criteria_weights_presets SET timeline_compliance = 0.12 WHERE timeline_compliance IS NULL")
    op.execute("UPDATE criteria_weights_presets SET technical_compliance = 0.18 WHERE technical_compliance IS NULL")
    op.execute("UPDATE criteria_weights_presets SET team_expertise = 0.10 WHERE team_expertise IS NULL")
    op.execute("UPDATE criteria_weights_presets SET functional_coverage = 0.15 WHERE functional_coverage IS NULL")
    op.execute("UPDATE criteria_weights_presets SET quality_assurance = 0.08 WHERE quality_assurance IS NULL")
    op.execute("UPDATE criteria_weights_presets SET development_methodology = 0.07 WHERE development_methodology IS NULL")
    op.execute("UPDATE criteria_weights_presets SET scalability = 0.05 WHERE scalability IS NULL")
    op.execute("UPDATE criteria_weights_presets SET communication = 0.05 WHERE communication IS NULL")
    op.execute("UPDATE criteria_weights_presets SET added_value = 0.05 WHERE added_value IS NULL")
    
    # Insert default system presets
    op.execute("""
        INSERT INTO criteria_weights_presets 
        (name, description, is_system, budget_compliance, timeline_compliance, technical_compliance, 
         team_expertise, functional_coverage, quality_assurance, development_methodology, 
         scalability, communication, added_value, created_at, updated_at)
        VALUES 
        ('balanced', 'Сбалансированное распределение весов по всем критериям', true, 
         0.15, 0.12, 0.18, 0.10, 0.15, 0.08, 0.07, 0.05, 0.05, 0.05, now(), now()),
        ('budget_focused', 'Повышенное внимание к финансовым аспектам', true,
         0.25, 0.15, 0.15, 0.08, 0.12, 0.05, 0.05, 0.05, 0.05, 0.05, now(), now()),
        ('technical_focused', 'Акцент на технических решениях и функциональности', true,
         0.10, 0.10, 0.25, 0.15, 0.20, 0.08, 0.07, 0.05, 0.05, 0.05, now(), now()),
        ('quality_focused', 'Приоритет контроля качества и надежности', true,
         0.12, 0.12, 0.15, 0.12, 0.15, 0.20, 0.08, 0.06, 0.05, 0.05, now(), now())
        ON CONFLICT (name) DO NOTHING
    """)
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_criteria_weights_presets_id'), table_name='criteria_weights_presets')
    op.drop_table('criteria_weights_presets')
    op.drop_index(op.f('ix_v3_analysis_documents_id'), table_name='v3_analysis_documents')
    op.drop_table('v3_analysis_documents')
    op.drop_index(op.f('ix_v3_analyses_id'), table_name='v3_analyses')
    op.drop_table('v3_analyses')
    # ### end Alembic commands ###